"""Prescribed second-order reference-response model (requirement R2).

The policy is trained to track ``xi(t)`` rather than the raw command ``u``.
``xi`` is generated by a critically damped second-order system with a box
constraint on its rate, one independent instance per decision channel.

This model is *prescribed*, not identified: the very same linear system becomes
the nominal dynamics of the downstream SE(3) MPC, so the discretisation used
here is part of the interface, not an implementation detail.

Continuous-time system, per channel::

    xi_ddot = omega_n^2 (u - xi) - 2 zeta omega_n xi_dot,   zeta = 1
    xi_dot in [-rate_limit, +rate_limit]

Discretisation
--------------
The linear part is advanced with the **exact** zero-order-hold transition
matrix, not a Euler step.  Two reasons, both of which matter:

1.  R2's acceptance criterion demands agreement with the analytic step response
    to within 1e-4.  Semi-implicit Euler at ``omega_n * dt = 0.1`` errs by
    roughly ``(omega_n dt)^2 / 2`` of the amplitude, i.e. ~4e-3 for a 0.4 rad
    step -- a factor of 40 too large.  The exact map is accurate to machine
    epsilon regardless of step size.
2.  The MPC will discretise the same continuous system, quite possibly at a
    different step size.  With exact ZOH matrices, training-time reference and
    plan-time prediction agree exactly; with Euler they disagree at O(dt) and
    that disagreement is indistinguishable from a genuine modelling error.

For a repeated eigenvalue ``lambda = -omega_n`` the matrix exponential is
``exp(A dt) = exp(-s) [[1+s, dt], [-omega_n^2 dt, 1-s]]`` with ``s = omega_n dt``
(``A + omega_n I`` is nilpotent).  Because the equilibrium for a constant ``u``
is ``(xi, xi_dot) = (u, 0)``, the map is applied to the *deviation* from that
equilibrium, which makes a command change a change of equilibrium rather than a
state reset -- exactly the R2 invariant "command resampling must not reset the
reference state".

Rate saturation
---------------
The limit is applied to ``xi_dot`` (a state), not to the acceleration, so the
system stays "linear dynamics + box constraint on a state" and the MPC stays a
QP.  R2's rationale is explicit about what saturation is for: small commands
keep full bandwidth, large commands *degenerate into a constant-velocity ramp*.

Getting that right needs one more step than clipping the endpoint.  Advancing
the exact linear map across the whole interval and clipping ``xi_dot`` only at
the end lets ``xi`` move faster than ``rate_limit`` *within* the interval -- on
a large command step the position increment reaches ~1.4x ``rate_limit * dt``.
Two things are wrong with that: it contradicts the continuous-time spec (where
``|dxi/dt| <= rate_limit`` holds pointwise, hence ``|dxi| <= rate_limit * dt``
over any interval), and the size of the violation scales with ``dt``, which
destroys the step-size independence the exact discretisation was chosen for.

So the update is piecewise, and exact in both pieces:

* not saturated -> the exact ZOH map (exact for the linear system),
* saturated     -> ``xi += clipped_rate * dt`` (exact for a ramp).

Only the one or two steps that cross the boundary carry O(dt) error.  A
saturated large step is therefore a true constant-velocity ramp at
``rate_limit``, and both regimes reproduce the same trajectory at any dt.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Iterable, Optional, Sequence, Tuple

import torch

from .command_layout import (
    BODY_HEIGHT,
    BODY_PITCH,
    DECISION_CHANNEL_NAMES,
    DECISION_CMD_INDEX,
    VX,
    VY,
    YAW_RATE,
)


@dataclass(frozen=True)
class ChannelSpec:
    """One MPC decision channel of the reference model.

    ``cmd_index`` is the column of ``commands_dog`` this channel reads.  The
    channel order and the command order are *not* the same (body pitch sits at
    command index 3, body height at 5), which is why this mapping is data and
    never hard-coded at the use sites.

    ``omega_n`` and ``rate_limit`` are starting values only; R8.2's calibration
    replaces them with 20th-percentile values measured from a stage-1 policy.
    """

    name: str
    cmd_index: int
    omega_n: float
    rate_limit: float


#: Starting values from the requirements document (R2).  MUST be replaced by
#: the R8.2 calibration output before any result is reported.
DEFAULT_CHANNELS: Tuple[ChannelSpec, ...] = (
    ChannelSpec(name="vx", cmd_index=VX, omega_n=8.0, rate_limit=1.2),
    ChannelSpec(name="vy", cmd_index=VY, omega_n=6.0, rate_limit=0.8),
    ChannelSpec(name="wyaw", cmd_index=YAW_RATE, omega_n=8.0, rate_limit=3.0),
    ChannelSpec(name="height", cmd_index=BODY_HEIGHT, omega_n=7.0, rate_limit=0.25),
    ChannelSpec(name="pitch", cmd_index=BODY_PITCH, omega_n=5.0, rate_limit=0.8),
)


def validate_channels(channels: Sequence[ChannelSpec]) -> None:
    """Check the invariants R2 states as design decisions, not preferences."""
    if not channels:
        raise ValueError("at least one channel is required")

    names = [c.name for c in channels]
    if len(set(names)) != len(names):
        raise ValueError(f"duplicate channel names: {names}")

    indices = [c.cmd_index for c in channels]
    if len(set(indices)) != len(indices):
        raise ValueError(f"duplicate cmd_index values: {indices}")

    for c in channels:
        if not c.omega_n > 0.0:
            raise ValueError(f"channel {c.name!r}: omega_n must be > 0, got {c.omega_n}")
        if not c.rate_limit > 0.0:
            raise ValueError(f"channel {c.name!r}: rate_limit must be > 0, got {c.rate_limit}")

    # R2 invariant: posture changes need differential front/rear leg thrust,
    # which the trot diagonal-support configuration authorises less of than the
    # symmetric push-off that changes height.  A reference model that asks for
    # the opposite is asking for something the plant cannot deliver.
    by_name = {c.name: c for c in channels}
    if "pitch" in by_name and "height" in by_name:
        if not by_name["pitch"].omega_n < by_name["height"].omega_n:
            raise ValueError(
                "R2 invariant violated: omega_n[pitch] must be strictly less than "
                f"omega_n[height], got {by_name['pitch'].omega_n} >= {by_name['height'].omega_n}"
            )


def build_channels(order, omega_n, rate_limit):
    """Assemble the channel table from plain config containers.

    ``omega_n`` and ``rate_limit`` are name-keyed mappings (that is what the
    R8.2 calibration writes out); ``cmd_index`` is deliberately *not*
    configurable -- it is a fact about the command vector layout, not a tunable,
    so it comes from ``command_layout`` and cannot drift per run.
    """
    index_of = dict(zip(DECISION_CHANNEL_NAMES, DECISION_CMD_INDEX))
    missing = [name for name in order if name not in index_of]
    if missing:
        raise ValueError(
            f"unknown response channel(s) {missing}; known: {list(index_of)}"
        )
    channels = tuple(
        ChannelSpec(
            name=name,
            cmd_index=index_of[name],
            omega_n=float(omega_n[name]),
            rate_limit=float(rate_limit[name]),
        )
        for name in order
    )
    validate_channels(channels)
    return channels


def critically_damped_step_response(
    amplitude: float, omega_n: float, t: torch.Tensor | float
) -> torch.Tensor | float:
    """Analytic step response ``A [1 - (1 + omega_n t) exp(-omega_n t)]``.

    Used by the R2 acceptance tests and by the R8.2 calibration script; kept
    here so the closed form lives next to the discretisation it validates.
    """
    if isinstance(t, torch.Tensor):
        wt = omega_n * t
        return amplitude * (1.0 - (1.0 + wt) * torch.exp(-wt))
    wt = omega_n * t
    return amplitude * (1.0 - (1.0 + wt) * math.exp(-wt))


class ReferenceModel:
    """Per-environment, per-channel reference trajectory generator.

    State is ``xi`` and ``xi_dot``, both ``(num_envs, num_channels)``.  The env
    owns the call schedule; this object owns nothing but its tensors.
    """

    def __init__(
        self,
        channels: Sequence[ChannelSpec],
        num_envs: int,
        dt: float,
        device: torch.device | str = "cpu",
        dtype: torch.dtype = torch.float32,
        zeta: float = 1.0,
    ) -> None:
        validate_channels(channels)
        if not dt > 0.0:
            raise ValueError(f"dt must be > 0, got {dt}")
        if abs(zeta - 1.0) > 1e-9:
            # Deliberate: R2 specifies critical damping because overshoot needs
            # extra deceleration authority, and that authority is the first
            # thing to run out on low friction / heavy payload domains -- which
            # makes overshoot the least reproducible quantity across domains.
            raise NotImplementedError(
                f"only critically damped (zeta=1) references are supported, got zeta={zeta}"
            )

        self.channels: Tuple[ChannelSpec, ...] = tuple(channels)
        self.num_envs = int(num_envs)
        self.num_channels = len(self.channels)
        self.dt = float(dt)
        self.zeta = float(zeta)
        self.device = torch.device(device)
        self.dtype = dtype

        def _row(values: Iterable[float]) -> torch.Tensor:
            return torch.tensor(list(values), device=self.device, dtype=self.dtype).unsqueeze(0)

        self.omega_n = _row(c.omega_n for c in self.channels)
        self.rate_limit = _row(c.rate_limit for c in self.channels)
        self.cmd_index = torch.tensor(
            [c.cmd_index for c in self.channels], device=self.device, dtype=torch.long
        )

        # Exact zero-order-hold transition matrix of the deviation state
        # z = [xi - u, xi_dot]; see the module docstring for the derivation.
        s = self.omega_n * self.dt
        decay = torch.exp(-s)
        self._a11 = decay * (1.0 + s)
        self._a12 = decay * self.dt
        self._a21 = -decay * self.omega_n * self.omega_n * self.dt
        self._a22 = decay * (1.0 - s)

        shape = (self.num_envs, self.num_channels)
        self.xi = torch.zeros(shape, device=self.device, dtype=self.dtype)
        self.xi_dot = torch.zeros(shape, device=self.device, dtype=self.dtype)
        self._pending_align = torch.zeros(self.num_envs, device=self.device, dtype=torch.bool)

    # ---------------------------------------------------------------- helpers

    @property
    def channel_names(self) -> Tuple[str, ...]:
        return tuple(c.name for c in self.channels)

    def gather_commands(self, commands_dog: torch.Tensor) -> torch.Tensor:
        """Pick the decision channels out of the full ``commands_dog`` buffer."""
        if commands_dog.shape[0] != self.num_envs:
            raise ValueError(
                f"expected {self.num_envs} rows, got {commands_dog.shape[0]}"
            )
        required = int(self.cmd_index.max().item()) + 1
        if commands_dog.shape[1] < required:
            raise ValueError(
                f"commands_dog has {commands_dog.shape[1]} columns but channel "
                f"mapping needs at least {required}"
            )
        return commands_dog.index_select(1, self.cmd_index)

    def normalized_rate(self) -> torch.Tensor:
        """``xi_dot`` scaled so the saturation boundary lands on +-1.

        Observation-facing: the channels carry different units (m/s^2 for the
        velocity channels, rad/s for pitch), so a shared observation scale would
        be meaningless.  Normalising by the limit is both dimensionless and
        semantically the right thing for the policy to see.
        """
        return self.xi_dot / self.rate_limit

    # ------------------------------------------------------------------ state

    def request_alignment(self, env_ids: torch.Tensor) -> None:
        """Mark environments whose reference must snap to the measured state.

        R2 invariant: the reference is aligned to the measurement **only** on
        environment reset, never on command resampling.  The alignment is
        deferred by one step on purpose: ``reset_idx`` runs after
        ``_reset_root_states``, at which point ``base_lin_vel`` and friends
        still hold the *pre-reset* values -- they are only refreshed at the top
        of the next ``post_physics_step``.  Snapping there would align to stale
        measurements.
        """
        if env_ids.numel() == 0:
            return
        self._pending_align[env_ids] = True

    def align_now(self, env_ids: torch.Tensor, measured: torch.Tensor) -> None:
        """Snap ``xi`` to ``measured`` and zero ``xi_dot`` for ``env_ids``."""
        if env_ids.numel() == 0:
            return
        self.xi[env_ids] = measured[env_ids].to(self.dtype)
        self.xi_dot[env_ids] = 0.0
        self._pending_align[env_ids] = False

    @property
    def has_pending_alignment(self) -> bool:
        return bool(self._pending_align.any().item())

    # ------------------------------------------------------------------- step

    def step(
        self, commands: torch.Tensor, measured: Optional[torch.Tensor] = None
    ) -> None:
        """Advance the reference by one control step.

        ``commands`` is ``(num_envs, num_channels)`` in channel order -- use
        :meth:`gather_commands` to build it from ``commands_dog``.  ``measured``
        is only consulted for environments with a pending alignment.
        """
        if commands.shape != (self.num_envs, self.num_channels):
            raise ValueError(
                f"commands must be {(self.num_envs, self.num_channels)}, got {tuple(commands.shape)}"
            )

        if self._pending_align.any():
            if measured is None:
                raise ValueError(
                    "environments are pending reference alignment but no measured "
                    "state was supplied; pass measured=... on the first step after reset"
                )
            pending = self._pending_align.nonzero(as_tuple=False).flatten()
            self.align_now(pending, measured)

        commands = commands.to(self.dtype)

        # Deviation from the equilibrium the current command implies.  A command
        # change moves the equilibrium; it never touches the state.
        deviation = self.xi - commands
        rate = self.xi_dot

        next_deviation = self._a11 * deviation + self._a12 * rate
        next_rate = self._a21 * deviation + self._a22 * rate

        clipped_rate = torch.clamp(next_rate, -self.rate_limit, self.rate_limit)
        saturated = clipped_rate != next_rate

        # Unsaturated: the exact linear map.  Saturated: a ramp at exactly the
        # limit, so the position honours |dxi| <= rate_limit * dt.  See the
        # module docstring for why the endpoint-clip alternative is wrong.
        self.xi = torch.where(saturated, self.xi + clipped_rate * self.dt, commands + next_deviation)
        self.xi_dot = clipped_rate

    # ------------------------------------------------------------------- misc

    def state_dict(self) -> dict:
        return {"xi": self.xi.clone(), "xi_dot": self.xi_dot.clone(),
                "pending_align": self._pending_align.clone()}

    def load_state_dict(self, state: dict) -> None:
        self.xi = state["xi"].to(device=self.device, dtype=self.dtype)
        self.xi_dot = state["xi_dot"].to(device=self.device, dtype=self.dtype)
        self._pending_align = state["pending_align"].to(device=self.device, dtype=torch.bool)
