#!/usr/bin/env python3
"""
Velocity-Sampled Full-Pose Trajectory Generator  —  difficulty-scaled

Trajectories are built from a SAMPLED velocity so the path length is exact and
stable (unlike the goal-attractor generators, where length only emerges).

Curriculum  (difficulty D — same spirit as langevin_traj_gen.py)
────────────────────────────────────────────────────────────────
  D ≤ point_max        →  a single held POINT  (position + held orientation)
  D small  (just above) →  SHORT + STRAIGHT path  (length ≈ length_min, ~no wander)
  D large              →  LONG + CURVY path      (length ≈ length_max, big wander)

Both the length AND the curviness scale with D:
  * length :  L(D) = lerp(length_min, length_max, t),  t = (D−point_max)/(1−point_max)
              — a short path fits straight; a long one must fold (⇒ curvy).
  * wander :  turn_sigma = D^wander_exp · disturb

Length is EXACT: a trapezoidal speed profile (rest→cruise→rest) is scaled so its
time-integral equals L; only the DIRECTION is steered (wander + bounded barrier,
grid, and command-cone avoidance), never the speed.

Attitude  (see pose_traj_gen.py)
────────────────────────────────
The EE orientation is generated by the position-conditioned reachable-orientation
tracker (pose_traj_gen.AttitudeSimulator): every pose is jointly feasible, and
the orientation difficulty scales with D as well (D small → near the feasible
mean, D large → more orientation variation).

Output per difficulty:
  testvel_D###.pt   — history_x/v [N,K,3], history_euler/quat/abg, target_length …
  testvel_D###.png  — 3D trajectories + EE triads + length & turn-angle stats

Usage:
  conda run -n roboduet python scripts/langevin_field_gen.py     # fields, once
  conda run -n roboduet python scripts/test_velocity.py
  conda run -n roboduet python scripts/test_velocity.py --show
"""

import argparse
import os
import sys
import time
from pathlib import Path

os.environ.setdefault('MPLCONFIGDIR', '/tmp/matplotlib')

import numpy as np
import torch
import yaml

import matplotlib
if '--show' not in sys.argv:
    matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.lines as mlines
from mpl_toolkits.mplot3d import Axes3D   # noqa: F401

# Shared machinery: fields + SDF queries (ltg), the feasible-attitude
# simulator + quaternion helpers (ptg), and the (drift-anchored) velocity
# trajectory simulator (tcur — the IsaacGym-facing library).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import langevin_traj_gen as ltg
import pose_traj_gen as ptg
from go1_gym.envs.roboduet.traj_gen.trajectory_curriculum import VelocityTrajectorySimulator, speed_profile, xyz_to_lpy  # noqa: F401



# ─────────────────────────────────────────────────────────────────────────────
# Config loading / diagnostics
# ─────────────────────────────────────────────────────────────────────────────

def load_generation_config(path: str) -> dict:
    with open(path) as f:
        cfg = yaml.safe_load(f)
    if 'generator' in cfg:
        return cfg

    # Backward compatibility for the older configs/test_velocity.yaml shape.
    # The canonical config is now configs/trajectory_generation.yaml.
    if 'base_config' not in cfg:
        raise KeyError("config must contain either 'generator' or 'base_config'")
    base = ltg.load_config(cfg['base_config'])
    lc = base.get('langevin', {})
    gc = base.get('generator', {})
    fg = base.get('field_gen', {})
    fields_path = Path(fg.get('save_dir', 'runs/langevin')) / \
                  fg.get('fields_filename', 'precomputed_fields.pt')
    merged = dict(cfg)
    merged['generator'] = {
        'N': lc.get('N', 5000),
        'K': lc.get('K', 300),
        'dt': lc.get('dt', 0.01),
        'device': gc.get('device', 'cuda'),
        'fields_path': str(fields_path),
    }
    return merged


def command_limit_report(history_x: torch.Tensor, vel_cfg: dict) -> str:
    limits = vel_cfg.get('command_limits')
    if not limits:
        return ''
    lpy = xyz_to_lpy(history_x.reshape(-1, 3))
    names = ('l', 'p', 'y')
    out_parts = []
    any_out = torch.zeros(lpy.shape[0], dtype=torch.bool, device=lpy.device)
    for i, key in enumerate(names):
        if key not in limits:
            continue
        lo, hi = float(limits[key][0]), float(limits[key][1])
        out = (lpy[:, i] < lo) | (lpy[:, i] > hi)
        any_out |= out
        out_parts.append(f"{key}_out={out.float().mean().item()*100:.1f}%")
    if not out_parts:
        return ''
    return f"  command : any_out={any_out.float().mean().item()*100:.1f}%  " + \
           "  ".join(out_parts)


# ─────────────────────────────────────────────────────────────────────────────
# Visualisation
# ─────────────────────────────────────────────────────────────────────────────

def visualize(sim, history_x, history_v, history_quat, D, length_range,
              viz_cfg, save_path, show):
    """3D trajectories + EE-frame triads  |  length histogram  |  turn-angle stats."""
    hist = history_x.cpu().numpy()
    vel  = history_v.cpu().numpy()
    quat = history_quat.cpu().numpy()
    L    = sim.target_length.cpu().numpy()
    N, K, _ = hist.shape
    fg = sim.fg
    gh, ground_z = fg.gh, fg.ground_z
    Lmin, Lmax = length_range
    n_traj   = min(int(viz_cfg.get('n_trajectories', 10)), N)
    n_triads = int(viz_cfg.get('n_triads', 7))
    tlen     = float(viz_cfg.get('triad_len', 0.10))

    rng    = np.random.default_rng(0)
    chosen = rng.choice(N, size=n_traj, replace=False)

    fig = plt.figure(figsize=(21, 7))
    ax  = fig.add_subplot(1, 3, 1, projection='3d')
    axL = fig.add_subplot(1, 3, 2)
    axT = fig.add_subplot(1, 3, 3)

    # ── 3D trajectories + EE triads ───────────────────────────────────────────
    gs = np.linspace(-gh * 0.95, gh * 0.95, 6)
    GX, GY = np.meshgrid(gs, gs)
    ax.plot_surface(GX, GY, np.full_like(GX, ground_z), alpha=0.08,
                    color='saddlebrown', linewidth=0)
    sdf = fg._field_curr[0, 0].cpu().numpy()
    lin = np.linspace(-gh, gh, fg.grid_res)
    iz, iy, ix = np.where(np.abs(sdf) < 0.04)
    if len(iz) > 2000:
        s = rng.choice(len(iz), 2000, replace=False)
        iz, iy, ix = iz[s], iy[s], ix[s]
    ax.scatter(lin[ix], lin[iy], lin[iz], s=0.6, alpha=0.04, color='steelblue')
    ltg._draw_box(ax, fg.body_box_center, fg.body_box_size, color='dimgray', alpha=0.20)

    span = max(Lmax - Lmin, 1e-6)
    basis = torch.eye(3)
    tri_steps = np.unique(np.linspace(0, K - 1, n_triads).astype(int))
    for idx in chosen:
        tr  = hist[idx]
        col = cm.viridis(float((L[idx] - Lmin) / span)) if sim.stage != 'point' \
              else cm.viridis(0.5)
        ax.plot(tr[:, 0], tr[:, 1], tr[:, 2], color=col, lw=1.1, alpha=0.9, zorder=10)
        ax.scatter(*tr[0], color=col, s=26, marker='o', edgecolors='k',
                   linewidths=0.3, zorder=11)
        q_sel = torch.from_numpy(quat[idx, tri_steps]).float()       # [T,4]
        p_sel = tr[tri_steps]
        for a, acol in enumerate(['red', 'green', 'blue']):          # EE X/Y/Z
            dvec = ptg.quat_apply(q_sel, basis[a]).numpy() * tlen
            for m in range(len(tri_steps)):
                ax.plot([p_sel[m, 0], p_sel[m, 0] + dvec[m, 0]],
                        [p_sel[m, 1], p_sel[m, 1] + dvec[m, 1]],
                        [p_sel[m, 2], p_sel[m, 2] + dvec[m, 2]],
                        color=acol, lw=1.3, alpha=0.9, zorder=12)
    ax.scatter(0, 0, 0, color='red', s=90, marker='o', edgecolors='darkred', zorder=20)
    ax.set_xlabel('X (m)'); ax.set_ylabel('Y (m)'); ax.set_zlabel('Z (m)')
    # outreach trajectories leave the workspace — widen the box to fit them
    lim = max(gh * 0.98, float(np.abs(hist[:, :, :2]).max()) * 1.05)
    zhi = max(gh * 0.98, float(hist[:, :, 2].max()) * 1.05)
    ax.set_xlim(-lim, lim); ax.set_ylim(-lim, lim); ax.set_zlim(ground_z - 0.05, zhi)
    try:
        ax.set_box_aspect([1, 1, 1])
    except (AttributeError, TypeError):
        pass
    ax.set_title(f'Velocity-Sampled Full-Pose Trajectories  ·  D = {D:.2f}  '
                 f'·  stage: {sim.stage}\n'
                 f'N = {N}  ·  colour = path length  ·  RGB triads = EE attitude',
                 fontsize=10, fontweight='bold', pad=8)

    # ── achieved path-length histogram ────────────────────────────────────────
    step_len = np.linalg.norm(np.diff(hist, axis=1), axis=-1)
    achieved = step_len.sum(axis=1)
    axL.hist(achieved, bins=30, color='mediumseagreen', edgecolor='k', alpha=0.85)
    axL.axvline(Lmin, color='red', ls='--', lw=0.9)
    axL.axvline(Lmax, color='red', ls='--', lw=0.9)
    axL.set_xlabel('achieved path length (m)'); axL.set_ylabel('trajectories')
    axL.set_title(f'Path length  ·  mean={achieved.mean():.2f}  '
                  f'[{achieved.min():.2f}, {achieved.max():.2f}] m\n'
                  f'max |achieved − target| = {np.abs(achieved - L).max()*1e3:.2f} mm',
                  fontsize=10, fontweight='bold')
    axL.grid(alpha=0.3)

    # ── per-step turn-angle distribution (straightness ↔ disturbance) ────────
    sp = np.linalg.norm(vel, axis=-1)
    vn = vel / np.clip(sp[..., None], 1e-9, None)
    cos = np.clip(np.sum(vn[:, 1:] * vn[:, :-1], axis=-1), -1, 1)
    ang = np.degrees(np.arccos(cos))
    moving = (sp[:, 1:] > 0.1) & (sp[:, :-1] > 0.1)
    a = ang[moving]
    if a.size > 0:
        axT.hist(a, bins=40, color='slateblue', edgecolor='k', alpha=0.85)
        axT.set_title(f'Direction smoothness  ·  D = {D:.2f}\n'
                      f'mean={a.mean():.2f}°  p99={np.percentile(a,99):.2f}°  '
                      f'max={a.max():.1f}°', fontsize=10, fontweight='bold')
    else:
        axT.text(0.5, 0.5, 'point stage — no motion', ha='center', va='center',
                 transform=axT.transAxes, fontsize=11)
        axT.set_title(f'Direction smoothness  ·  D = {D:.2f}',
                      fontsize=10, fontweight='bold')
    axT.set_xlabel('per-step turn angle (deg)'); axT.set_ylabel('steps')
    axT.grid(alpha=0.3)

    plt.tight_layout()
    if save_path:
        os.makedirs(os.path.dirname(save_path) or '.', exist_ok=True)
        plt.savefig(save_path, dpi=140, bbox_inches='tight')
        print(f"  Saved → {save_path}")
    if show:
        plt.show()
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser(
        description='Velocity-sampled, length-controlled full-pose trajectory generator.')
    ap.add_argument('--config', default='configs/trajectory_generation.yaml')
    ap.add_argument('--show', action='store_true',
                    help='display the 3D plot interactively (rotate / zoom)')
    ap.add_argument('--D', type=float, default=None,
                    help='generate only this single difficulty (pair with --show)')
    args = ap.parse_args()

    cfg = load_generation_config(args.config)

    gen_cfg  = cfg.get('generator', {})
    vel_cfg  = cfg['velocity']
    att_cfg  = cfg.get('attitude', {})
    out_cfg  = cfg.get('output', {})
    viz_cfg  = cfg.get('visualization', {})

    N   = int(gen_cfg.get('N',  5000))
    K   = int(gen_cfg.get('K',  300))
    DT  = float(gen_cfg.get('dt', 0.01))
    dev = str(gen_cfg.get('device', 'cuda'))
    device = dev if (dev != 'cuda' or torch.cuda.is_available()) else 'cpu'
    length_range = (float(vel_cfg['length_min']), float(vel_cfg['length_max']))

    # ── load the pre-computed fields ──────────────────────────────────────────
    fields_pt = Path(gen_cfg.get('fields_path', 'runs/langevin/precomputed_fields.pt'))
    if not fields_pt.exists():
        raise FileNotFoundError(
            f"Pre-computed fields not found at {fields_pt}\n"
            f"Run first:  conda run -n roboduet python scripts/langevin_field_gen.py")
    ckpt = torch.load(fields_pt, map_location='cpu', weights_only=False)
    for key in ('field_static', 'field_dynamic', 'field_body', 'field_orient'):
        if key not in ckpt:
            raise KeyError(f"{key} missing from {fields_pt} — re-run langevin_field_gen.py")
    grid_half = float(ckpt['grid_half'])
    fg = ltg.FieldGenerator(
        field_static    = ckpt['field_static'],
        field_dynamic   = ckpt['field_dynamic'],
        field_body      = ckpt['field_body'],
        grid_half       = grid_half,
        ground_z        = float(ckpt['ground_z']),
        device          = device,
        body_box_center = ckpt.get('body_box_center', (0.0, 0.0, 0.0)),
        body_box_size   = ckpt.get('body_box_size', (0.3762, 0.13, 0.114)),
    )
    field_orient  = ckpt['field_orient']
    orient_limits = list(ckpt.get('orient_limits', (1.4137, 1.0472, 1.3090)))

    save_dir = Path(out_cfg.get('save_dir', 'runs/test_velocity'))
    save_dir.mkdir(parents=True, exist_ok=True)
    pt_pre   = out_cfg.get('pt_prefix', 'testvel')
    plot_pre = out_cfg.get('plot_prefix', 'testvel')

    raw_d = cfg.get('difficulties', [0.0, 0.5, 1.0])
    difficulties = [raw_d] if isinstance(raw_d, (int, float)) else list(raw_d)
    if args.D is not None:                       # --D : run/show just one difficulty
        difficulties = [args.D]

    print(f"Device     : {device.upper()}")
    print(f"Particles  : {N}  |  Steps : {K}  |  dt : {DT} s")
    print(f"Curriculum : D≤{vel_cfg['point_max']:g} point · "
          f"length L(D)∈[{length_range[0]}, {length_range[1]}] m  ·  "
          f"curviness ∝ D\n")

    for D in difficulties:
        D = float(D)
        print(f"── Difficulty D = {D:.2f}  {'─'*44}")
        # ── position ──────────────────────────────────────────────────────────
        sim = VelocityTrajectorySimulator(fg, D, N, K, DT, vel_cfg, device)
        history_x, history_v = sim.simulate()

        # ── attitude (position-conditioned feasible orientation) ──────────────
        att = ptg.AttitudeSimulator(D, sim.stage, N, K, DT, att_cfg,
                                    field_orient, grid_half, orient_limits, device)
        history_euler = att.simulate(history_x)
        history_quat  = ptg.euler_to_quat(history_euler)
        history_abg   = ptg.quat_to_abg(history_quat)

        # ── validity / curriculum check ──────────────────────────────────────
        flat = history_x.reshape(-1, 3)
        sv, _ = fg.query_field(fg._field_curr, flat)
        bv, _ = fg.query_field(fg.field_body,  flat)
        if sim.stage != 'point':
            achieved = (history_x[:, 1:] - history_x[:, :-1]).norm(dim=-1).sum(dim=1)
            err = (achieved - sim.target_length).abs().max().item()
            # Net XY displacement & XY bounding-box span — quantifies how far
            # the trajectory travels in the floor plane.  This is the metric
            # that tells you the dog's BASE has to translate to follow:
            # a long path that folds in on itself has tiny net XY, while a
            # drift-anchored path scales net XY with L.
            xy = history_x[:, :, :2]
            net_xy = (xy[:, -1] - xy[:, 0]).norm(dim=-1)                   # [N]
            span_xy = (xy.max(dim=1).values - xy.min(dim=1).values).norm(dim=-1)
            ratio = (net_xy / achieved.clamp(min=1e-6)).mean().item()
            print(f"  length  : mean={achieved.mean():.3f} m  "
                  f"[{achieved.min():.2f}, {achieved.max():.2f}]  "
                  f"max|err|={err*1e3:.3f} mm")
            print(f"  XY span : net displacement mean={net_xy.mean():.2f} m "
                  f"[{net_xy.min():.2f}, {net_xy.max():.2f}]  ·  "
                  f"bbox diag mean={span_xy.mean():.2f} m  ·  "
                  f"net/L = {ratio*100:.0f}%  (⇒ base must travel ≥ net XY)")
        cmd_report = command_limit_report(history_x, vel_cfg)
        if cmd_report:
            print(cmd_report)
        grid_out = (history_x.abs() > fg.gh).any(dim=-1).float().mean().item() * 100
        if sim.stage == 'outreach':
            print(f"  grid    : {grid_out:.2f}% of samples outside SDF grid (should be ~0)")
        if sim.stage == 'outreach':
            # outreach trajectories roam freely; each must have SOME hard content
            svN, bvN = sv.reshape(N, K), bv.reshape(N, K)
            hard = (svN > 0.0) | (bvN < 0.0)              # out of arm reach OR in the body
            frac = hard.float().mean(dim=1) * 100         # [N] per-trajectory hard %
            out_pct  = (sv > 0.0).float().mean().item() * 100
            body_pct = (bv < 0.0).float().mean().item() * 100
            print(f"  free-roam : {out_pct:.0f}% of all points out of arm reach · "
                  f"{body_pct:.0f}% inside the body")
            print(f"  hard part : every traj {frac.min().item():.0f}–{frac.max().item():.0f}% "
                  f"unfollowable (mean {frac.mean().item():.0f}%)  ⇒  base motion required")
        else:
            pct_ws   = (sv < 0.02).float().mean().item() * 100
            pct_body = (bv > 0.0).float().mean().item() * 100
            print(f"  valid   : {pct_ws:.1f}% in workspace · {pct_body:.1f}% off body")

        d_tag   = f'D{int(round(D * 100)):03d}'
        pt_path = save_dir / f'{pt_pre}_{d_tag}.pt'
        torch.save({'history_x':     history_x.cpu(),
                    'history_v':     history_v.cpu(),
                    'history_lpy':   xyz_to_lpy(history_x).cpu(),
                    'history_euler': history_euler.cpu(),
                    'history_quat':  history_quat.cpu(),
                    'history_abg':   history_abg.cpu(),
                    'target_length': sim.target_length.cpu(),
                    'D': D, 'N': N, 'K_STEPS': K, 'DT': DT, 'stage': sim.stage}, pt_path)
        print(f"  Saved → {pt_path}")

        visualize(sim, history_x, history_v, history_quat, D, length_range,
                  viz_cfg, save_path=str(save_dir / f'{plot_pre}_{d_tag}.png'),
                  show=args.show)
        print()

    print("Done.")


if __name__ == '__main__':
    main()
