"""Go1 robot profile."""

from .core import ConfigProfile


GO1_PROFILE = ConfigProfile(
    name="go1",
    allow_new=True,
    overrides={
        "init_state.pos": [0.0, 0.0, 0.34],
        "init_state.default_joint_angles": {
            "FL_hip_joint": 0.1,
            "RL_hip_joint": 0.1,
            "FR_hip_joint": -0.1,
            "RR_hip_joint": -0.1,
            "FL_thigh_joint": 0.8,
            "RL_thigh_joint": 1.0,
            "FR_thigh_joint": 0.8,
            "RR_thigh_joint": 1.0,
            "FL_calf_joint": -1.5,
            "RL_calf_joint": -1.5,
            "FR_calf_joint": -1.5,
            "RR_calf_joint": -1.5,
        },
        "control.control_type": "P",
        "control.stiffness": {"joint": 35.0},
        "control.damping": {"joint": 1.0},
        "control.action_scale": 0.25,
        "control.hip_scale_reduction": 0.5,
        "control.decimation": 4,
        "asset.file": "{MINI_GYM_ROOT_DIR}/resources/robots/go1/urdf/go1.urdf",
        "asset.foot_name": "foot",
        "asset.penalize_contacts_on": ["thigh", "calf"],
        "asset.terminate_after_contacts_on": ["base"],
        "asset.self_collisions": 0,
        "asset.flip_visual_attachments": False,
        "asset.fix_base_link": False,
        "asset.hip_joints": {"hip"},
        "asset.render_sphere": False,
        "rewards.soft_dof_pos_limit": 0.9,
        "rewards.base_height_target": 0.34,
        "reward_scales.torques": -0.0001,
        "reward_scales.action_rate": -0.01,
        "reward_scales.dof_pos_limits": -10.0,
        "reward_scales.orientation": -5.0,
        "terrain.mesh_type": "trimesh",
        "terrain.measure_heights": False,
        "terrain.terrain_noise_magnitude": 0.0,
        "terrain.teleport_robots": True,
        "terrain.border_size": 50.0,
        "terrain.terrain_proportions": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
        "terrain.curriculum": False,
        "env.num_observations": 42,
        "env.observe_vel": False,
        "env.num_envs": 4000,
        "commands.heading_command": False,
        "commands.resampling_time": 10.0,
        "commands.command_curriculum": True,
        "commands.num_lin_vel_bins": 30,
        "commands.num_ang_vel_bins": 30,
        "commands.lin_vel_x": [-0.6, 0.6],
        "commands.lin_vel_y": [-0.6, 0.6],
        "commands.ang_vel_yaw": [-1.0, 1.0],
        "domain_rand.randomize_base_mass": True,
        "domain_rand.added_mass_range": [-1.0, 3.0],
        "domain_rand.push_robots": False,
        "domain_rand.max_push_vel_xy": 0.5,
        "domain_rand.randomize_friction": True,
        "domain_rand.friction_range": [0.05, 4.5],
        "domain_rand.randomize_restitution": True,
        "domain_rand.restitution_range": [0.0, 1.0],
        "domain_rand.restitution": 0.5,
        "domain_rand.randomize_com_displacement": True,
        "domain_rand.com_displacement_range": [-0.1, 0.1],
        "domain_rand.randomize_motor_strength": True,
        "domain_rand.motor_strength_range": [0.9, 1.1],
        "domain_rand.randomize_Kp_factor": False,
        "domain_rand.Kp_factor_range": [0.8, 1.3],
        "domain_rand.randomize_Kd_factor": False,
        "domain_rand.Kd_factor_range": [0.5, 1.5],
        "domain_rand.rand_interval_s": 6.0,
    },
)
