"""Complete editable RoboDuet task profile.

This is the only task-level defaults file used by RoboDuet.  Keys are full
``Cfg`` paths so a value can be found and changed without following an
order-dependent Go1 -> WTW -> arm-asset recipe chain. Framework defaults and
profile composition live beside this file in the flat ``config`` package; any
field can be overridden here by adding its dotted path to
:data:`ROBODUET_OVERRIDES`.

Derived observation sizes and runtime feature switches are intentionally kept
out of this table.  They are calculated in ``core.py`` from these
source values and the command-line options.
"""

import math

from .core import ConfigProfile


ROBOT_ASSET_FILES = {
    "go1": "{MINI_GYM_ROOT_DIR}/resources/robots/arx5p2Go1/urdf/arx5p2Go1.urdf",
    "go2": "{MINI_GYM_ROOT_DIR}/resources/robots/go2/urdf/arx5go2.urdf",
}


# One flat table makes precedence explicit: every path occurs exactly once.
ROBODUET_OVERRIDES = {
    # Robot initial state and low-level control.
    "init_state.pos": [0.0, 0.0, 0.34],
    "init_state.default_joint_angles": {
        "FL_hip_joint": 0.1,
        "RL_hip_joint": 0.1,
        "FR_hip_joint": -0.1,
        "RR_hip_joint": -0.1,
        "FL_thigh_joint": 0.8,
        "RL_thigh_joint": 1.0,
        "FR_thigh_joint": 0.8,
        "RR_thigh_joint": 1.0,
        "FL_calf_joint": -1.5,
        "RL_calf_joint": -1.5,
        "FR_calf_joint": -1.5,
        "RR_calf_joint": -1.5,
        "widow_waist": 0.0,
        "widow_shoulder": 0.0,
        "widow_elbow": 0.0,
        "forearm_roll": 0.0,
        "widow_wrist_angle": 0.0,
        "widow_wrist_rotate": 0.0,
        "widow_forearm_roll": 0.0,
        "gripper": 0.0,
        "widow_left_finger": 0.0,
        "widow_right_finger": 0.0,
        "zarx_j1": 0.0,
        "zarx_j2": 0.0,
        "zarx_j3": 0.0,
        "zarx_j4": 0.0,
        "zarx_j5": 0.0,
        "zarx_j6": 0.0,
        "zarx_j7": 0.0,
        "zarx_j8": 0.0,
    },
    "control.control_type": "M",
    "control.stiffness": {"joint": 35.0, "widow": 5.0, "zarx": 5.0, "zarx_j3": 20.0},
    "control.damping": {"joint": 1.0},
    "control.action_scale": 0.25,
    "control.hip_scale_reduction": 0.5,
    "control.decimation": 4,
    "control.update_obs_freq": 20,

    # Asset values common to both robots. The URDF path is selected below from
    # ROBOT_ASSET_FILES after parsing --robot.
    "asset.foot_name": "foot",
    "asset.penalize_contacts_on": ["base", "trunk", "wrist", "thigh", "calf", "Head"],
    "asset.arm_contact_bodies": [],
    "asset.terminate_after_contacts_on": [""],
    "asset.hip_joints": {"hip"},
    "asset.self_collisions": 1,
    "asset.flip_visual_attachments": False,
    "asset.fix_base_link": False,
    "asset.render_sphere": True,

    # Environment and policy layout source values. Observation widths are
    # derived later and therefore are not editable constants here.
    "env.keep_arm_fixed": True,
    "env.num_actions": 18,
    "env.num_observation_history": 30,
    "env.priv_observe_arm_mount_tf": True,
    "env.priv_observe_friction": True,
    "env.priv_observe_ground_friction": False,
    "env.priv_observe_restitution": True,
    "env.priv_observe_base_mass": True,
    "env.priv_observe_com_displacement": True,
    "env.priv_observe_motor_strength": False,
    "env.priv_observe_motor_offset": False,
    "env.priv_observe_joint_friction": True,
    "env.priv_observe_Kp_factor": True,
    "env.priv_observe_Kd_factor": True,
    "env.priv_observe_dof_damping": True,
    "env.priv_observe_body_height": False,
    "env.priv_observe_gravity": False,
    "env.priv_observe_body_velocity": False,
    "env.priv_observe_clock_inputs": False,
    "env.priv_observe_desired_contact_states": False,
    "env.priv_observe_vel": True,
    "env.priv_observe_high_freq_goal": False,
    "env.priv_observe_motion": False,
    "env.priv_observe_gravity_transformed_motion": False,
    "env.priv_observe_friction_indep": False,
    "env.priv_observe_ground_friction_per_foot": False,
    "env.priv_observe_contact_forces": False,
    "env.priv_observe_foot_displacement": False,
    "env.priv_observe_gravity_transformed_foot_displacement": False,
    "env.observe_vel": False,
    "env.observe_yaw": False,
    "env.observe_gait_commands": True,
    "env.observe_timing_parameter": False,
    "env.observe_clock_inputs": True,
    "env.observe_two_prev_actions": False,
    "env.num_scalar_observations": 70,
    "env.record_video": False,
    "env.recording_width_px": 500,
    "env.recording_height_px": 320,
    "env.recording_mode": "COLOR",
    "env.num_recording_envs": 1,
    "env.recording_frame_stride": 1,
    "env.recording_overlay_text": True,
    "env.recording_overlay_trajectory": True,
    "env.debug_viz": False,
    "env.all_agents_share": False,

    # Stage-1 arm disturbance curriculum.
    "env.stage1_arm_fixed_fraction": 0.1,
    "env.stage1_arm_saturation_fraction": 0.8,
    "env.stage1_arm_accel_resample_time_s": 0.01,
    "env.stage1_arm_zero_accel_probability": 0.3,
    "env.stage1_arm_zero_vel_probability": 0.005,
    "env.stage1_arm_max_accel": 10.0,
    "env.stage1_arm_max_vel": 5.0,
    "env.stage1_arm_max_offset": 999.0,
    "env.stage1_arm_init_dof_pos_noise": 1.0,

    # Dog command distribution and limits.
    "commands.use_dynamic_gait": False,
    "commands.num_commands": 15,
    "commands.heading_command": False,
    "commands.resampling_time": 10.0,
    "commands.command_curriculum": True,
    "commands.global_reference": False,
    "commands.distributional_commands": False,
    "commands.num_lin_vel_bins": 30,
    "commands.num_ang_vel_bins": 30,
    "commands.lin_vel_x": [-1.0, 1.0],
    "commands.lin_vel_y": [-0.6, 0.6],
    "commands.ang_vel_yaw": [-1.0, 1.0],
    "commands.body_height_cmd": [-0.2, 0.2],
    "commands.gait_frequency_cmd_range": [1.0, 6.0],
    "commands.gait_phase_cmd_range": [0.0, 0.01],
    "commands.gait_offset_cmd_range": [0.0, 0.01],
    "commands.gait_bound_cmd_range": [0.0, 0.01],
    "commands.gait_duration_cmd_range": [0.49, 0.5],
    "commands.footswing_height_range": [0.06, 0.061],
    "commands.body_pitch_range": [-0.4, 0.4],
    "commands.body_roll_range": [-0.4, 0.4],
    "commands.stance_width_range": [0.10, 0.45],
    "commands.stance_length_range": [0.25, 0.45],
    "commands.limit_vel_x": [-1.0, 1.0],
    "commands.limit_vel_y": [-0.6, 0.6],
    "commands.limit_vel_yaw": [-1.0, 1.0],
    "commands.limit_body_height": [-0.2, 0.2],
    "commands.limit_gait_frequency": [1.0, 6.0],
    "commands.limit_gait_phase": [0.0, 0.01],
    "commands.limit_gait_offset": [0.0, 0.01],
    "commands.limit_gait_bound": [0.0, 0.01],
    "commands.limit_gait_duration": [0.49, 0.5],
    "commands.limit_footswing_height": [0.06, 0.061],
    "commands.limit_body_pitch": [-0.4, 0.4],
    "commands.limit_body_roll": [-0.4, 0.4],
    "commands.limit_stance_width": [0.10, 0.45],
    "commands.limit_stance_length": [0.25, 0.45],
    "commands.num_bins_vel_x": 21,
    "commands.num_bins_vel_y": 3,
    "commands.num_bins_vel_yaw": 21,
    "commands.num_bins_body_height": 1,
    "commands.num_bins_gait_frequency": 1,
    "commands.num_bins_gait_phase": 1,
    "commands.num_bins_gait_offset": 1,
    "commands.num_bins_gait_bound": 1,
    "commands.num_bins_gait_duration": 1,
    "commands.num_bins_footswing_height": 1,
    "commands.num_bins_body_roll": 1,
    "commands.num_bins_body_pitch": 1,
    "commands.num_bins_stance_width": 1,
    "commands.exclusive_phase_offset": False,
    "commands.pacing_offset": False,
    "commands.binary_phases": True,
    "commands.gaitwise_curricula": True,
    "commands.T_force_range": [2.0, 4.0],
    "commands.add_force_thres": 0.3,

    # Terrain and reset curriculum.
    "terrain.mesh_type": "plane",
    "terrain.measure_heights": False,
    "terrain.terrain_noise_magnitude": 0.0,
    "terrain.teleport_robots": False,
    "terrain.border_size": 0.0,
    "terrain.terrain_proportions": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
    "terrain.curriculum": False,
    "terrain.num_cols": 30,
    "terrain.num_rows": 30,
    "terrain.terrain_width": 5.0,
    "terrain.terrain_length": 5.0,
    "terrain.x_init_range": 0.2,
    "terrain.y_init_range": 0.2,
    "terrain.z_init_range": 0.5,
    "terrain.yaw_init_range": 3.14,
    "terrain.roll_init_range": 3.14,
    "terrain.pitch_init_range": 3.14,
    "terrain.reset_curriculum": True,
    "terrain.reset_curriculum_initial_fraction": 0.1,
    "terrain.reset_curriculum_start_threshold": 0.7,
    "terrain.reset_curriculum_reward_threshold": 0.7,
    "terrain.reset_curriculum_success_ema_alpha": 0.05,
    "terrain.reset_curriculum_growth_iterations": 5000,
    "terrain.teleport_thresh": 0.3,
    "terrain.center_robots": True,
    "terrain.center_span": 4,
    "terrain.horizontal_scale": 0.10,

    # Locomotion and arm rewards.
    "rewards.soft_dof_pos_limit": 0.9,
    "rewards.base_height_target": 0.30,
    "rewards.use_terminal_foot_height": False,
    "rewards.use_terminal_body_height": True,
    "rewards.terminal_body_height": 0.17,
    "rewards.use_terminal_roll_pitch": True,
    "rewards.terminal_body_ori": 1.6,
    "rewards.manip_weight_lpy": 3.0,
    "rewards.manip_weight_rpy": 1.0,
    "rewards.kappa_gait_probs": 0.07,
    "rewards.gait_force_sigma": 100.0,
    "rewards.gait_vel_sigma": 10.0,
    "rewards.reward_container_name": "Rewards",
    "rewards.only_positive_rewards": False,
    "rewards.only_positive_rewards_ji22_style": True,
    "rewards.sigma_rew_neg": 0.02,
    "reward_scales.torques": -0.0001,
    "reward_scales.action_rate": -0.001,
    "reward_scales.action_smoothness_1": -0.1,
    "reward_scales.action_smoothness_2": -0.1,
    "reward_scales.dof_pos_limits": -10.0,
    "reward_scales.dof_vel": -1e-4,
    "reward_scales.dof_pos": -0.0,
    "reward_scales.jump": 10.0,
    "reward_scales.loco_energy": -0.00004,
    "reward_scales.feet_contact_forces": 0.0,
    "reward_scales.feet_slip": -0.04,
    "reward_scales.raibert_heuristic": -10.0,
    "reward_scales.feet_impact_vel": -0.0,
    "reward_scales.feet_clearance": -0.0,
    "reward_scales.feet_clearance_cmd": -0.0,
    "reward_scales.feet_clearance_cmd_linear": -30.0,
    "reward_scales.orientation": 0.0,
    "reward_scales.orientation_control": -5.0,
    "reward_scales.base_height": -30.0,
    "reward_scales.lin_vel_z": -0.02,
    "reward_scales.ang_vel_xy": -0.001,
    "reward_scales.feet_air_time": 0.0,
    "reward_scales.hop_symmetry": 0.0,
    "reward_scales.tracking_contacts_shaped_force": 4.0,
    "reward_scales.tracking_contacts_shaped_vel": 4.0,
    "reward_scales.collision": -10.0,

    # WBC hybrid reward configuration.
    "hybrid.num_actions": 18,
    "hybrid.plan_vel": False,
    "hybrid.use_vision": False,
    "hybrid.rewards.terminal_body_height": 0.17,
    "hybrid.rewards.use_terminal_body_height": True,
    "hybrid.rewards.use_terminal_roll": False,
    "hybrid.rewards.use_terminal_pitch": False,
    "hybrid.rewards.terminal_body_roll": 0.10,
    "hybrid.rewards.terminal_body_pitch": 0.2,
    "hybrid.rewards.terminal_body_pitch_roll": math.radians(80.0),
    "hybrid.rewards.headupdown_thres": 0.1,
    "hybrid.reward_scales.jump": 5.0,
    "hybrid.reward_scales.arm_manip_commands_tracking_combine": 1.0,
    "hybrid.reward_scales.vis_manip_commands_tracking_lpy": 1.0,
    "hybrid.reward_scales.vis_manip_commands_tracking_rpy": 1.0,
    "hybrid.reward_scales.orientation_heuristic": -2.0,
    "hybrid.reward_scales.orientation_control": -10.0,
    "hybrid.reward_scales.hip_action_l2": -0.05,
    "hybrid.reward_scales.raibert_heuristic": -0.0,
    "hybrid.reward_scales.arm_dogcommand_smoothness_1": -0.1,
    "hybrid.reward_scales.arm_control_limits": -0.0001,
    "hybrid.reward_scales.traj_track": 0.0,
    "hybrid.reward_scales.trajectory_current_tracking": 0.0,
    "hybrid.reward_scales.trajectory_completion_time": 0.0,
    "hybrid.reward_scales.arm_delta_vel_cmd": 0.0,
    "hybrid.reward_scales.ee_smoothness": 0.0,
    "hybrid.reward_scales.arm_contact": -1.0,

    # Arm commands, trajectory curriculum and controller.
    "arm.num_actions_arm": 6,
    "arm.arm_num_observation_history": 30,
    "arm.arm_num_commands": 6,
    "arm.num_actions_arm_cd": 8,
    "arm.use_adaptation_module": False,
    "arm.commands.l": [0.3, 0.77],
    "arm.commands.p": [-math.pi * 0.45, math.pi * 0.45],
    "arm.commands.y": [-math.pi / 2.0, math.pi / 2.0],
    "arm.commands.roll_ee": [-math.pi * 0.45, math.pi * 0.45],
    "arm.commands.pitch_ee": [-math.radians(60.0), math.radians(60.0)],
    "arm.commands.yaw_ee": [-math.radians(75.0), math.radians(75.0)],
    "arm.commands.T_traj": [2.0, 3.0],
    "arm.commands.T_force_range": [1.0, 4.0],
    "arm.commands.add_force_thres": 0.3,
    "arm.trajectory.enabled": False,
    "arm.trajectory.traj_type": ["point"],
    "arm.trajectory.window_offsets": [0, 1, 2, 4, 8, 16, 32, 64],
    "arm.trajectory.num_waypoints": 96,
    "arm.trajectory.start_radius": 0.0,
    "arm.trajectory.length_range": [0.05, 1.0],
    "arm.trajectory.s_curve_amplitude_range": [0.02, 0.12],
    "arm.trajectory.s_curve_frequency": 1.0,
    "arm.trajectory.circle_radius": 0.5,
    "arm.trajectory.circle_turns": 1.0,
    "arm.trajectory.completion_time_range": [2.0, 5.0],
    "arm.trajectory.completion_pos_threshold": 0.05,
    "arm.trajectory.completion_rot_threshold": 0.25,
    "arm.trajectory.curriculum_levels": 6,
    "arm.trajectory.curriculum_success_threshold": 0.6,
    "arm.trajectory.delta_vel_limit": [0.4, 0.25, 0.6],
    "arm.trajectory.user_cmd_mode": "zero",
    "arm.trajectory.user_lin_vel_x": [-0.3, 0.3],
    "arm.trajectory.user_lin_vel_y": [-0.2, 0.2],
    "arm.trajectory.user_ang_vel_yaw": [-0.4, 0.4],
    "arm.trajectory.pos_error_scale": 4.0,
    "arm.trajectory.rot_error_scale": 1.0,
    "arm.trajectory.completion_time_sigma": 1.0,
    "arm.trajectory.dog_command_smoothing_alpha": 0.2,
    "arm.trajectory.dog_command_smoothness_weight_delta_vel": 1.0,
    "arm.trajectory.dog_command_smoothness_weight_body_pose": 1.0,
    "arm.trajectory.dog_command_smoothness_weight_gait": 2.0,
    "arm.trajectory.stage2_base_unlock_curriculum": True,
    "arm.trajectory.stage2_base_unlock_success_threshold": 0.9,
    "arm.trajectory.stage2_base_unlock_success_ema_alpha": 0.05,
    "arm.trajectory.stage2_base_unlock_ramp_iterations": 1000,
    "arm.trajectory.stage2_base_unlock_force_point_until_unlocked": True,
    "arm.obs_scales.l": 1.0,
    "arm.obs_scales.p": 1.0,
    "arm.obs_scales.y": 1.0,
    "arm.obs_scales.wx": 1.0,
    "arm.obs_scales.wy": 1.0,
    "arm.obs_scales.wz": 1.0,
    "arm.control.stiffness_arm": {
        "zarx": 50.0,
        "zarx_j1": 40.0,
        "zarx_j2": 70.0,
        "zarx_j3": 70.0,
        "zarx_j4": 25.0,
        "zarx_j5": 25.0,
        "zarx_j6": 25.0,
        "zarx_j7": 50.0,
        "zarx_j8": 50.0,
    },
    "arm.control.damping_arm": {
        "zarx": 20.0,
        "zarx_j1": 3.0,
        "zarx_j2": 15.0,
        "zarx_j3": 15.0,
        "zarx_j4": 2.0,
        "zarx_j5": 2.0,
        "zarx_j6": 2.0,
        "zarx_j7": 20.0,
        "zarx_j8": 20.0,
    },

    # Dog policy/controller layout.
    "dog.num_actions_loco": 12,
    "dog.dog_num_observation_history": 30,
    "dog.dog_num_commands": 6,
    "dog.dog_actions": 12,
    "dog.use_adaptation_module": False,
    "dog.control.stiffness_leg": {"joint": 35.0},
    "dog.control.damping_leg": {"joint": 1.0},

    # Domain randomization.
    "domain_rand.rand_interval_s": 4.0,
    "domain_rand.randomize_rigids_after_start": False,
    "domain_rand.randomize_friction": True,
    "domain_rand.friction_range": [0.1, 3.0],
    "domain_rand.randomize_friction_indep": False,
    "domain_rand.randomize_restitution": True,
    "domain_rand.restitution_range": [0.0, 0.4],
    "domain_rand.restitution": 0.5,
    "domain_rand.randomize_base_mass": True,
    "domain_rand.added_mass_range": [-2.0, 2.0],
    "domain_rand.randomize_com_displacement": False,
    "domain_rand.com_displacement_range": [-0.15, 0.15],
    "domain_rand.randomize_ground_friction": True,
    "domain_rand.ground_friction_range": [0.0, 0.0],
    "domain_rand.randomize_motor_strength": True,
    "domain_rand.motor_strength_range": [0.9, 1.1],
    "domain_rand.randomize_motor_offset": True,
    "domain_rand.motor_offset_range": [-0.02, 0.02],
    "domain_rand.randomize_Kp_factor": True,
    "domain_rand.Kp_factor_range": [0.8, 1.3],
    "domain_rand.randomize_Kd_factor": True,
    "domain_rand.Kd_factor_range": [0.5, 1.5],
    "domain_rand.randomize_gravity": True,
    "domain_rand.gravity_range": [-1.0, 1.0],
    "domain_rand.gravity_rand_interval_s": 8.0,
    "domain_rand.gravity_impulse_duration": 0.99,
    "domain_rand.push_robots": False,
    "domain_rand.max_push_vel_xy": 0.5,
    "domain_rand.lag_timesteps": 6,
    "domain_rand.randomize_lag_timesteps": False,
    "domain_rand.randomize_action_delay": True,
    "domain_rand.tile_height_range": [-0.0, 0.0],
    "domain_rand.tile_height_curriculum": False,
    "domain_rand.tile_height_update_interval": 1_000_000,
    "domain_rand.tile_height_curriculum_step": 0.01,
    "domain_rand.randomize_end_effector_force": False,
    "domain_rand.max_force": 15.0,
    "domain_rand.max_force_offset": 0.01,
    "domain_rand.randomize_mount_pos": True,
    "domain_rand.mount_pos_range": [[-0.05, 0.05], [-0.02, 0.02], [-0.05, 0.05]],
    "domain_rand.mount_pos_buckets": 16,
    "domain_rand.mount_pos_bucket_seed": 1234,
    "domain_rand.mount_joint_name": "zarx5p2_mount",
    "domain_rand.stage1_arm.randomize_Kp_factor": True,
    "domain_rand.stage1_arm.Kp_factor_range": [0.5, 1.5],
    "domain_rand.stage1_arm.randomize_Kd_factor": True,
    "domain_rand.stage1_arm.Kd_factor_range": [0.2, 2.0],
    "domain_rand.stage1_arm.randomize_motor_strength": True,
    "domain_rand.stage1_arm.motor_strength_range": [0.7, 1.3],
    "domain_rand.stage1_arm.randomize_motor_offset": True,
    "domain_rand.stage1_arm.motor_offset_range": 0.05,
    "domain_rand.stage1_arm.randomize_link_mass": True,
    "domain_rand.stage1_arm.link_mass_range": [0.1, 2.0],
    "domain_rand.stage1_arm.randomize_link_com": True,
    "domain_rand.stage1_arm.link_com_range": 0.1,
    "domain_rand.stage2_arm.randomize_Kp_factor": True,
    "domain_rand.stage2_arm.Kp_factor_range": [0.9, 1.1],
    "domain_rand.stage2_arm.randomize_Kd_factor": True,
    "domain_rand.stage2_arm.Kd_factor_range": [0.9, 1.1],
    "domain_rand.stage2_arm.randomize_motor_strength": True,
    "domain_rand.stage2_arm.motor_strength_range": [0.85, 1.15],
    "domain_rand.stage2_arm.randomize_motor_offset": True,
    "domain_rand.stage2_arm.motor_offset_range": 0.025,
    "domain_rand.stage2_arm.randomize_link_mass": True,
    "domain_rand.stage2_arm.link_mass_range": [0.85, 1.15],
    "domain_rand.stage2_arm.randomize_link_com": True,
    "domain_rand.stage2_arm.link_com_range": 0.01,

    # Curriculum thresholds and privileged-observation normalization.
    "curriculum_thresholds.tracking_ang_vel": 0.7,
    "curriculum_thresholds.tracking_lin_vel": 0.8,
    "curriculum_thresholds.tracking_contacts_shaped_vel": 0.90,
    "curriculum_thresholds.tracking_contacts_shaped_force": 0.90,
    "normalization.friction_range": [0.0, 1.0],
    "normalization.ground_friction_range": [0.0, 1.0],
    "normalization.clip_actions": 10.0,
    "normalization.Kp_factor_range": [0.5, 1.5],
    "normalization.Kd_factor_range": [0.2, 2.0],
    "normalization.dof_damping_range": [0.0, 10.0],
}


# Non-Cfg constants used while deriving hybrid rewards and feature layouts.
HYBRID_REWARD_FACTORS = {
    "tracking_lin_vel": 0.7,
    "tracking_ang_vel": 0.5,
    "arm_energy": -0.00004,
    "arm_dof_vel": 0.01,
    "arm_dof_acc": 0.01,
    "arm_action_rate": 0.001,
    "arm_action_smoothness_1": 0.001,
    "arm_action_smoothness_2": 0.001,
}


FEATURE_LAYOUT = {
    "rot6d_command_dims": 3,
    "trajectory_plan_action_dims": 3,
    "dynamic_gait_command_dims": 5,
    "dynamic_gait_plan_action_dims": 6,
}


TRAJECTORY_REWARD_CONFIG = {
    "trajectory_current_tracking": 1.0,
    "trajectory_completion_time": 0.5,
    "arm_delta_vel_cmd": -0.05,
    "ee_smoothness": -1e-4,
}


DYNAMIC_GAIT_BIN_CONFIG = {
    "commands.num_bins_gait_frequency": 11,
    "commands.num_bins_footswing_height": 5,
    "commands.num_bins_gait_duration": 3,
    "commands.num_bins_stance_width": 3,
    "commands.num_bins_stance_length": 3,
}


ROBODUET_PROFILE = ConfigProfile(
    name="roboduet",
    overrides=ROBODUET_OVERRIDES,
    allow_new=True,
)
