"""Walk-These-Ways locomotion profile."""

from .core import ConfigProfile


WTW_PROFILE = ConfigProfile(
    name="wtw",
    allow_new=True,
    overrides={
        "commands.num_lin_vel_bins": 30,
        "commands.num_ang_vel_bins": 30,
        "commands.distributional_commands": True,
        "commands.num_commands": 15,
        "commands.resampling_time": 10.0,
        "commands.lin_vel_x": [-1.0, 1.0],
        "commands.lin_vel_y": [-0.6, 0.6],
        "commands.ang_vel_yaw": [-1.0, 1.0],
        "commands.body_height_cmd": [-0.2, 0.2],
        "commands.gait_frequency_cmd_range": [1.0, 6.0],
        "commands.gait_phase_cmd_range": [0.0, 0.01],
        "commands.gait_offset_cmd_range": [0.0, 0.01],
        "commands.gait_bound_cmd_range": [0.0, 0.01],
        "commands.gait_duration_cmd_range": [0.49, 0.5],
        "commands.footswing_height_range": [0.06, 0.061],
        "commands.body_pitch_range": [-0.4, 0.4],
        "commands.body_roll_range": [-0.2, 0.2],
        "commands.stance_width_range": [0.10, 0.45],
        "commands.stance_length_range": [0.25, 0.45],
        "commands.limit_vel_x": [-1.0, 1.0],
        "commands.limit_vel_y": [-0.6, 0.6],
        "commands.limit_vel_yaw": [-1.0, 1.0],
        "commands.limit_body_height": [-0.2, 0.2],
        "commands.limit_gait_frequency": [1.0, 6.0],
        "commands.limit_gait_phase": [0.0, 0.01],
        "commands.limit_gait_offset": [0.0, 0.01],
        "commands.limit_gait_bound": [0.0, 0.01],
        "commands.limit_gait_duration": [0.49, 0.5],
        "commands.limit_footswing_height": [0.06, 0.061],
        "commands.limit_body_pitch": [-0.4, 0.4],
        "commands.limit_body_roll": [-0.2, 0.2],
        "commands.limit_stance_width": [0.10, 0.45],
        "commands.limit_stance_length": [0.25, 0.45],
        "commands.num_bins_vel_x": 21,
        "commands.num_bins_vel_y": 3,
        "commands.num_bins_vel_yaw": 21,
        "commands.num_bins_body_height": 1,
        "commands.num_bins_gait_frequency": 1,
        "commands.num_bins_gait_phase": 1,
        "commands.num_bins_gait_offset": 1,
        "commands.num_bins_gait_bound": 1,
        "commands.num_bins_gait_duration": 1,
        "commands.num_bins_footswing_height": 1,
        "commands.num_bins_body_roll": 1,
        "commands.num_bins_body_pitch": 1,
        "commands.num_bins_stance_width": 1,
        "commands.exclusive_phase_offset": False,
        "commands.pacing_offset": False,
        "commands.binary_phases": True,
        "commands.gaitwise_curricula": True,
        "curriculum_thresholds.tracking_ang_vel": 0.7,
        "curriculum_thresholds.tracking_lin_vel": 0.8,
        "curriculum_thresholds.tracking_contacts_shaped_vel": 0.90,
        "curriculum_thresholds.tracking_contacts_shaped_force": 0.90,
        "control.control_type": "actuator_net",
        "env.priv_observe_motion": False,
        "env.priv_observe_gravity_transformed_motion": False,
        "env.priv_observe_friction_indep": False,
        "env.priv_observe_friction": True,
        "env.priv_observe_restitution": True,
        "env.priv_observe_base_mass": False,
        "env.priv_observe_gravity": False,
        "env.priv_observe_com_displacement": False,
        "env.priv_observe_ground_friction": False,
        "env.priv_observe_ground_friction_per_foot": False,
        "env.priv_observe_motor_strength": False,
        "env.priv_observe_motor_offset": False,
        "env.priv_observe_Kp_factor": False,
        "env.priv_observe_Kd_factor": False,
        "env.priv_observe_body_velocity": False,
        "env.priv_observe_body_height": False,
        "env.priv_observe_desired_contact_states": False,
        "env.priv_observe_contact_forces": False,
        "env.priv_observe_foot_displacement": False,
        "env.priv_observe_gravity_transformed_foot_displacement": False,
        "env.num_privileged_obs": 2,
        "env.num_observation_history": 30,
        "env.observe_two_prev_actions": True,
        "env.observe_yaw": False,
        "env.num_observations": 70,
        "env.num_scalar_observations": 70,
        "env.observe_gait_commands": True,
        "env.observe_timing_parameter": False,
        "env.observe_clock_inputs": True,
        "domain_rand.lag_timesteps": 6,
        "domain_rand.randomize_lag_timesteps": True,
        "domain_rand.randomize_rigids_after_start": False,
        "domain_rand.randomize_friction_indep": False,
        "domain_rand.randomize_friction": True,
        "domain_rand.friction_range": [0.1, 3.0],
        "domain_rand.randomize_restitution": True,
        "domain_rand.restitution_range": [0.0, 0.4],
        "domain_rand.randomize_base_mass": True,
        "domain_rand.added_mass_range": [-1.0, 3.0],
        "domain_rand.randomize_gravity": True,
        "domain_rand.gravity_range": [-1.0, 1.0],
        "domain_rand.gravity_rand_interval_s": 8.0,
        "domain_rand.gravity_impulse_duration": 0.99,
        "domain_rand.randomize_com_displacement": False,
        "domain_rand.com_displacement_range": [-0.15, 0.15],
        "domain_rand.randomize_ground_friction": True,
        "domain_rand.ground_friction_range": [0.0, 0.0],
        "domain_rand.randomize_motor_strength": True,
        "domain_rand.motor_strength_range": [0.9, 1.1],
        "domain_rand.randomize_motor_offset": True,
        "domain_rand.motor_offset_range": [-0.02, 0.02],
        "domain_rand.push_robots": False,
        "domain_rand.randomize_Kp_factor": True,
        "domain_rand.randomize_Kd_factor": True,
        "domain_rand.rand_interval_s": 4.0,
        "domain_rand.tile_height_range": [-0.0, 0.0],
        "domain_rand.tile_height_curriculum": False,
        "domain_rand.tile_height_update_interval": 1_000_000,
        "domain_rand.tile_height_curriculum_step": 0.01,
        "terrain.border_size": 0.0,
        "terrain.mesh_type": "plane",
        "terrain.num_cols": 30,
        "terrain.num_rows": 30,
        "terrain.terrain_width": 5.0,
        "terrain.terrain_length": 5.0,
        "terrain.x_init_range": 0.2,
        "terrain.y_init_range": 0.2,
        "terrain.z_init_range": 0.5,
        "terrain.yaw_init_range": 3.14,
        "terrain.roll_init_range": 3.14,
        "terrain.pitch_init_range": 3.14,
        "terrain.reset_curriculum": True,
        "terrain.reset_curriculum_initial_fraction": 0.1,
        "terrain.reset_curriculum_start_threshold": 0.7,
        "terrain.reset_curriculum_reward_threshold": 0.7,
        "terrain.reset_curriculum_success_ema_alpha": 0.05,
        "terrain.reset_curriculum_growth_iterations": 5000,
        "terrain.teleport_thresh": 0.3,
        "terrain.teleport_robots": False,
        "terrain.center_robots": True,
        "terrain.center_span": 4,
        "terrain.horizontal_scale": 0.10,
        "rewards.use_terminal_foot_height": False,
        "rewards.use_terminal_body_height": True,
        "rewards.terminal_body_height": 0.05,
        "rewards.use_terminal_roll_pitch": True,
        "rewards.terminal_body_ori": 1.6,
        "rewards.base_height_target": 0.30,
        "rewards.kappa_gait_probs": 0.07,
        "rewards.gait_force_sigma": 100.0,
        "rewards.gait_vel_sigma": 10.0,
        "rewards.reward_container_name": "Rewards",
        "rewards.only_positive_rewards": False,
        "rewards.only_positive_rewards_ji22_style": True,
        "rewards.sigma_rew_neg": 0.02,
        "reward_scales.feet_contact_forces": 0.0,
        "reward_scales.feet_slip": -0.04,
        "reward_scales.action_rate": -0.001,
        "reward_scales.action_smoothness_1": -0.1,
        "reward_scales.action_smoothness_2": -0.1,
        "reward_scales.dof_vel": -1e-4,
        "reward_scales.dof_pos": -0.0,
        "reward_scales.jump": 10.0,
        "reward_scales.raibert_heuristic": -10.0,
        "reward_scales.feet_impact_vel": -0.0,
        "reward_scales.feet_clearance": -0.0,
        "reward_scales.feet_clearance_cmd": -0.0,
        "reward_scales.feet_clearance_cmd_linear": -30.0,
        "reward_scales.orientation": 0.0,
        "reward_scales.orientation_control": -5.0,
        "reward_scales.lin_vel_z": -0.02,
        "reward_scales.ang_vel_xy": -0.001,
        "reward_scales.feet_air_time": 0.0,
        "reward_scales.hop_symmetry": 0.0,
        "reward_scales.tracking_contacts_shaped_force": 4.0,
        "reward_scales.tracking_contacts_shaped_vel": 4.0,
        "reward_scales.collision": -10.0,
        "normalization.friction_range": [0.0, 1.0],
        "normalization.ground_friction_range": [0.0, 1.0],
        "normalization.clip_actions": 10.0,
    },
)
