#!/bin/bash

#PBS -N roboduet
#PBS -P CFP03-CF-003
#PBS -j oe
#PBS -k oed
#PBS -l walltime=12:00:00
#PBS -l select=1:ngpus=8:ncpus=64
###PBS -l select=1:ngpus=2
###PBS -l select=1:ngpus=4
###PBS -l select=1:ngpus=8
###PBS -l select=2:ngpus=8

job_name="roboduet"
set -euo pipefail

cd /home/svu/e1192548/Projects/WBC/RoboDuet

PYTHONCMD_1="python scripts/auto_train.py --headless --sim_device cuda:0 --dyna_gait --num_envs 4096 --num_steps_per_env 24 --num_mini_batches 4 --num_learning_iterations 30000 --train_stage stage1 --run_name "stage1_larger_cmd_range_no_arm_contact"

PYTHONCMD_2="python scripts/auto_train.py --headless --sim_device cuda:0 --dyna_gait --num_envs 4096 --num_steps_per_env 32 --num_mini_batches 4 --num_learning_iterations 22500 --train_stage stage1 --run_name "stage1_larger_cmd_range_no_arm_contact"

PYTHONCMD_3="python scripts/auto_train.py --headless --sim_device cuda:0 --dyna_gait --num_envs 4096 --num_steps_per_env 48 --num_mini_batches 8 --num_learning_iterations 15000 --train_stage stage1 --run_name "stage1_larger_cmd_range_no_arm_contact"

PYTHONCMD_4="python scripts/auto_train.py --headless --sim_device cuda:0 --dyna_gait --num_envs 8192 --num_steps_per_env 24 --num_mini_batches 4 --num_learning_iterations 15000 --train_stage stage1 --run_name "stage1_larger_cmd_range_no_arm_contact"

PYTHONCMD_5="python scripts/auto_train.py --headless --sim_device cuda:0 --dyna_gait --num_envs 8192 --num_steps_per_env 32 --num_mini_batches 8 --num_learning_iterations 11250 --train_stage stage1 --run_name "stage1_larger_cmd_range_no_arm_contact"

PYTHONCMD_6="python scripts/auto_train.py --headless --sim_device cuda:0 --dyna_gait --num_envs 16384 --num_steps_per_env 24 --num_mini_batches 6 --num_learning_iterations 11250 --train_stage stage1 --run_name "stage1_larger_cmd_range_no_arm_contact"

PYTHONCMD_7="python scripts/auto_train.py --headless --sim_device cuda:0 --dyna_gait --num_envs 20480 --num_steps_per_env 24 --num_mini_batches 6 --num_learning_iterations 11250 --train_stage stage1 --run_name "stage1_larger_cmd_range_no_arm_contact"

PYTHONCMD_8="python scripts/auto_train.py --headless --sim_device cuda:0 --dyna_gait --num_envs 32768 --num_steps_per_env 24 --num_mini_batches 8 --num_learning_iterations 11250 --train_stage stage1 --run_name "stage1_larger_cmd_range_no_arm_contact"

# PYTHONCMD_9="python scripts/auto_train.py --headless --sim_device cuda:0 --dyna_gait --num_envs 40960 --num_steps_per_env 24 --num_mini_batches 10 --num_learning_iterations 11250 --train_stage stage1 --run_name "stage1_larger_cmd_range_no_arm_contact"

preprocess() {
	LOG_FILE="tmp/logs/${job_name}.${PBS_JOBID}.log"
	exec >"$LOG_FILE" 2>&1

	set -x

	CACHE_DIR="/scratch/$USER/AppData"
	image="/scratch/$USER/Apptainer/ubuntu-desktop_24.04-cu12.6.2-isaac.sif"

	echo "------------------------------"
	echo "PBS_JOBID: $PBS_JOBID"
	echo "Running on host: $(hostname)"
	echo "Working directory: $(pwd)"
	echo "Image: $image"
	echo "Log file: $LOG_FILE"
	echo "------------------------------"

	nvidia-smi
	df -h

	echo "------------------------------"
	echo "Running on GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader)"
	echo "Running on NVIDIA driver version: $(nvidia-smi --query-gpu=driver_version --format=csv,noheader)"
	echo "------------------------------"

	module load singularity
}
preprocess

run_container() {
	local gpu_id="$1"
	local python_cmd="$2"

	echo "------------------------------"
	echo "Running container on GPU $gpu_id with command: $python_cmd"
	echo "------------------------------"

	CUDA_VISIBLE_DEVICES="$gpu_id" PYTHONCMD="$python_cmd" singularity exec "$image" bash <<'EOF' &
#!/bin/bash

set -euo pipefail
set -x

echo "------------------------------"
echo "INSIDE CONTAINER"
echo "Container host: $(hostname)"
echo "Container pwd: $(pwd)"
echo "CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-}"
echo "------------------------------"

nvidia-smi

source /opt/miniconda3/etc/profile.d/conda.sh
conda activate /opt/miniconda3/envs/isaacgym
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
export PYTHONPATH="${PYTHONPATH:-}:/home/svu/e1192548/Projects/WBC/RoboDuet"
export TORCH_EXTENSIONS_DIR=/scratch/$USER/.cache/torch_extensions
mkdir -p $TORCH_EXTENSIONS_DIR

$PYTHONCMD
EOF
}

run_container 0 "$PYTHONCMD_1"
run_container 1 "$PYTHONCMD_2"
run_container 2 "$PYTHONCMD_3"
run_container 3 "$PYTHONCMD_4"
run_container 4 "$PYTHONCMD_5"
run_container 5 "$PYTHONCMD_6"
run_container 6 "$PYTHONCMD_7"
run_container 7 "$PYTHONCMD_8"

wait

echo "------------------------------"
echo "After singularity"
echo "Job finished at: $(date)"
echo "------------------------------"
